name: Image Build
on:
  create:
    tags:
      - lambda/v*

jobs:
  go-image-build:
    uses:  tommzn/github-ci/.github/workflows/go.lambda.image.build.yml@v1.0.4
    secrets:
      cr-pat: ${{ secrets.CR_PAT }}